### ISSUE TITLE
+n doesn't show up on stat bonuses when built for production

### ISSUE THREAD

**Issue by robfletcher** [robfletcher/dungeon-world-sheets#14]
For some reason the CSS rule 
```css
  .bonus-positive:before {
    content: '+';
  }
```
is excluded from the generated stylesheet. Works fine in dev mode.
